#if !canImport(ObjectiveC)
import XCTest

extension SquareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SquareTests = [
        ("testSquare", testSquare),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SquareTests.__allTests__SquareTests),
    ]
}
#endif
